# -*- coding: utf-8 -*-
import json, unicodedata, re

def slugify(text):
    text = unicodedata.normalize('NFD', text).encode('ascii', 'ignore').decode('utf-8')
    text = re.sub(r'[^a-zA-Z0-9]+', '_', text).strip('_').lower()
    return text

# Define lists of words for each category:
# (word, level, emoji, hint, example, color)

ANIMAUX = [
    # Level 1
    ("coq", 1, "🐓", "L'oiseau de la ferme qui chante cocorico à l'aube.", "Le coq réveille toute la basse-cour.", "#fef3c7"),
    ("rat", 1, "🐀", "Petit rongeur rusé avec une longue queue fine.", "Le rat se cache dans un trou.", "#e2e8f0"),
    ("pie", 1, "🐦", "Oiseau noir et blanc connu pour aimer les objets brillants.", "La pie jacasse perchée sur la branche.", "#f1f5f9"),
    ("oie", 1, "🪿", "Grand oiseau blanc qui cacarde près de la mare.", "L'oie surveille fièrement ses petits.", "#f8fafc"),
    ("ver", 1, "🪱", "Petit animal sans pattes qui creuse dans la terre.", "Le ver de terre aide le potager.", "#ffedd5"),
    ("pou", 1, "🪲", "Tout petit insecte qui adore se cacher dans les cheveux.", "On passe le peigne pour chasser le pou.", "#fee2e2"),
    ("paon", 1, "🦚", "Magnifique oiseau qui fait la roue avec ses plumes.", "Le paon déploie sa queue magique.", "#cffafe"),
    ("veau", 1, "🐮", "Le petit de la vache qui boit du bon lait.", "Le petit veau galope dans l'enclos.", "#ffedd5"),
    ("bouc", 1, "🐐", "Le mâle de la chèvre avec de belles cornes.", "Le bouc a une jolie barbiche.", "#fef3c7"),
    ("âne", 1, "🫏", "Animal doux et patient qui fait hi-han.", "L'âne porte de lourds paniers.", "#e2e8f0"),
    ("cerf", 1, "🦌", "Le seigneur de la forêt coiffé de grands bois.", "Le cerf brame au coucher du soleil.", "#fed7aa"),
    ("thon", 1, "🐟", "Grand poisson très rapide nageant en haute mer.", "Le thon bondit hors de l'eau bleue.", "#dbeafe"),
    ("chat", 1, "🐱", "Il ronronne et adore chasser les souris.", "Le chat boit son lait.", "#ffedd5"),
    ("loup", 1, "🐺", "Il hurle à la lune dans la forêt.", "Le loup vit dans les bois.", "#e2e8f0"),
    ("ours", 1, "🐻", "Un grand animal poilu qui aime le miel.", "L'ours dort tout l'hiver.", "#fed7aa"),
    ("lion", 1, "🦁", "Le roi de la savane avec une crinière.", "Le lion rugit très fort.", "#fef3c7"),

    # Level 2
    ("chien", 2, "🐶", "Le meilleur ami qui aboie et remue la queue.", "Le chien court après la balle.", "#fef3c7"),
    ("lapin", 2, "🐰", "Il a de longues oreilles et adore les carottes.", "Le petit lapin sautille dans l'herbe.", "#f3e8ff"),
    ("singe", 2, "🐵", "Il saute de branche en branche et fait des grimaces.", "Le singe mange une banane.", "#fef3c7"),
    ("tigre", 2, "🐯", "Grand félin fauve avec des rayures noires.", "Le tigre se cache dans la jungle.", "#ffedd5"),
    ("poule", 2, "🐔", "Elle picore des graines et pond des œufs frais.", "La poule caquette dans la cour.", "#fef3c7"),
    ("vache", 2, "🐮", "Elle broute l'herbe dans le pré et fait Meuh.", "La vache a de belles taches.", "#f1f5f9"),
    ("cheval", 2, "🐴", "Il galope dans le pré et hennit joyeusement.", "Le cheval saute l'obstacle.", "#fed7aa"),
    ("biche", 2, "🦌", "La femelle du cerf, très gracieuse et rapide.", "La biche bondit au fond des bois.", "#ffedd5"),
    ("poney", 2, "🐴", "Un petit cheval très docile parfait pour les enfants.", "Je monte sur un gentil poney.", "#fed7aa"),
    ("zèbre", 2, "🦓", "Cousin du cheval vêtu de rayures blanches et noires.", "Le zèbre broute dans la plaine africaine.", "#f1f5f9"),
    ("panda", 2, "🐼", "Gros nounours noir et blanc qui croque du bambou.", "Le panda géant grimpe dans l'arbre.", "#f8fafc"),
    ("koala", 2, "🐨", "Petit marsupial d'Australie qui dort dans l'eucalyptus.", "Le koala s'accroche à la branche.", "#e2e8f0"),
    ("canard", 2, "🦆", "Il barbote sur la mare et fait coin-coin.", "Les canards nagent en file indienne.", "#fef3c7"),
    ("cygne", 2, "🦢", "Grand oiseau au long cou glissant gracieusement sur l'eau.", "Le cygne blanc nage sur le lac.", "#f8fafc"),
    ("aigle", 2, "🦅", "Rapace majestueux volant très haut dans le ciel.", "L'aigle plane au-dessus des sommets.", "#fed7aa"),
    ("faucon", 2, "🦅", "Oiseau de proie qui plonge en piqué à toute vitesse.", "Le faucon a un regard perçant.", "#fed7aa"),
    ("hibou", 2, "🦉", "Oiseau nocturne avec des aigrettes sur la tête.", "Le hibou hulule au clair de lune.", "#ede9fe"),
    ("loutre", 2, "🦦", "Petit mammifère joueur qui nage le ventre en l'air.", "La loutre plonge dans la rivière.", "#fed7aa"),
    ("taupe", 2, "🐾", "Elle vit sous terre et creuse de petits monticules.", "La taupe fabrique une taupinière.", "#e2e8f0"),
    ("souris", 2, "🐭", "Petite bête grise avec un S muet à la fin.", "La petite souris grignote le fromage.", "#e2e8f0"),
    ("mouton", 2, "🐑", "Il a une épaisse laine blanche et fait bêê.", "Le mouton broute dans le pré.", "#f8fafc"),
    ("chèvre", 2, "🐐", "Animal agile qui aime grimper sur les rochers.", "La chèvre donne du bon lait.", "#fef3c7"),
    ("taureau", 2, "🐂", "Le mâle puissant de la vache avec de grandes cornes.", "Le taureau veille sur le troupeau.", "#fed7aa"),
    ("lézard", 2, "🦎", "Petit reptile qui adore se chauffer au soleil.", "Le lézard file entre les pierres.", "#dcfce7"),
    ("serpent", 2, "🐍", "Reptile sans pattes qui ondule doucement dans l'herbe.", "Le serpent change de peau.", "#dcfce7"),

    # Level 3
    ("tortue", 3, "🐢", "Elle marche lentement avec sa carapace solide.", "La tortue rentre dans sa carapace.", "#dcfce7"),
    ("requin", 3, "🦈", "Grand poisson prédateur avec un aileron pointu.", "Le requin nage dans l'océan.", "#dbeafe"),
    ("girafe", 3, "🦒", "Le plus grand animal du monde grâce à son très long cou.", "La girafe mange les feuilles au sommet.", "#fef3c7"),
    ("renard", 3, "🦊", "Animal roux très rusé avec une belle queue touffue.", "Le renard rôde près du poulailler.", "#ffedd5"),
    ("chouette", 3, "🦉", "Oiseau de nuit sans aigrettes qui voit dans le noir.", "La chouette veille sur la forêt.", "#ede9fe"),
    ("baleine", 3, "🐋", "Le plus grand mammifère marin qui souffle un geyser.", "La baleine chante sous l'eau.", "#dbeafe"),
    ("dauphin", 3, "🐬", "Mammifère marin très joueur qui s'écrit avec PH !", "Le dauphin fait des sauts dans l'eau.", "#e0f2fe"),
    ("phoque", 3, "🦭", "Mammifère marin aux nageoires courtes qui glisse sur la glace.", "Le phoque plonge dans l'eau glacée.", "#cffafe"),
    ("morse", 3, "🦭", "Gros animal de l'Arctique avec deux longues défenses.", "Le morse se repose sur la banquise.", "#e2e8f0"),
    ("castor", 3, "🦫", "Bâtisseur hors pair qui construit des barrages de bois.", "Le castor coupe du bois avec ses dents.", "#fed7aa"),
    ("hérisson", 3, "🦔", "Petite boule couverte de piquants qui se roule en boule.", "Le hérisson se promène dans le jardin.", "#fed7aa"),
    ("écureuil", 3, "🐿️", "Petit rongeur roux qui cache des noisettes dans les arbres.", "L'écureuil saute de branche en branche.", "#ffedd5"),
    ("marmotte", 3, "🐿️", "Elle siffle en montagne et hiberne tout l'hiver.", "La marmotte prend le soleil en altitude.", "#fed7aa"),
    ("crapaud", 3, "🐸", "Amphibien bosselé qui se déplace en marchant.", "Le crapaud gobe les mouches la nuit.", "#dcfce7"),
    ("panthère", 3, "🐆", "Grand félin noir ou tacheté très furtif.", "La panthère bondit avec souplesse.", "#f1f5f9"),
    ("léopard", 3, "🐆", "Félin aux superbes taches en forme de rosettes.", "Le léopard dort sur une haute branche.", "#fef3c7"),
    ("guépard", 3, "🐆", "L'animal terrestre le plus rapide du monde.", "Le guépard sprinte à toute allure.", "#fef3c7"),
    ("jaguar", 3, "🐆", "Puissant félin d'Amérique du Sud qui aime nager.", "Le jaguar chasse près du fleuve.", "#ffedd5"),
    ("caméléon", 3, "🦎", "Reptile capable de changer de couleur pour se camoufler.", "Le caméléon tourne ses yeux indépendamment.", "#dcfce7"),
    ("iguane", 3, "🦎", "Grand lézard végétarien avec une crête sur le dos.", "L'iguane prend le soleil tropical.", "#dcfce7"),
    ("araignée", 3, "🕷️", "Elle tisse une magnifique toile géométrique en soie.", "L'araignée répare sa toile soyeuse.", "#ede9fe"),
    ("scorpion", 3, "🦂", "Arachnide du désert avec deux pinces et un dard recourbé.", "Le scorpion se cache sous un rocher.", "#fed7aa"),
    ("homard", 3, "🦞", "Grand crustacé des fonds marins doté de deux fortes pinces.", "Le homard se cache dans une crevasse.", "#fee2e2"),
    ("crevette", 3, "🦐", "Petit crustacé rose qui nage à reculons.", "La crevette frétille dans le filet.", "#fee2e2"),
    ("poulpe", 3, "🐙", "Mollusque marin très intelligent doté de huit tentacules.", "Le poulpe projette un nuage d'encre.", "#ede9fe"),
    ("calmar", 3, "🦑", "Céphalopode marin très rapide avec dix tentacules.", "Le calmar file comme une flèche dans l'eau.", "#f3e8ff"),
    ("escargot", 3, "🐌", "Il sort sa maison sur son dos dès qu'il commence à pleuvoir.", "L'escargot bave doucement sur la feuille.", "#fef3c7"),
    ("limace", 3, "🐌", "Cousine de l'escargot qui voyage sans coquille.", "La limace glisse sur l'herbe fraîche.", "#ecfccb"),

    # Level 4
    ("grenouille", 4, "🐸", "Petite bête verte qui coasse et saute dans la mare !", "La grenouille saute sur le nénuphar.", "#dcfce7"),
    ("papillon", 4, "🦋", "Insecte aux deux ailes multicolores avec deux L.", "Le papillon butine les fleurs.", "#dbeafe"),
    ("éléphant", 4, "🐘", "Le plus gros animal terrestre avec une grande trompe et PH !", "L'éléphant boit avec sa trompe.", "#e2e8f0"),
    ("dinosaure", 4, "🦖", "Animal géant préhistorique comme le T-Rex.", "Le grand dinosaure rugit.", "#dcfce7"),
    ("kangourou", 4, "🦘", "Il bondit très haut et porte son petit dans sa poche.", "Le kangourou fait de grands bonds.", "#fed7aa"),
    ("flamant", 4, "🦩", "Grand oiseau rose qui dort souvent sur une seule patte.", "Le flamant rose plonge son bec dans l'eau.", "#fce7f3"),
    ("pélican", 4, "🪶", "Grand oiseau de mer avec une immense poche sous le bec.", "Le pélican pêche des poissons frais.", "#e0f2fe"),
    ("autruche", 4, "🐦", "Le plus grand oiseau du monde qui court très vite sans voler.", "L'autruche court à toute allure.", "#fed7aa"),
    ("manchot", 4, "🐧", "Oiseau qui ne vole pas mais nage comme un champion dans l'eau glacée.", "Le manchot glisse sur le ventre.", "#f1f5f9"),
    ("pingouin", 4, "🐧", "Oiseau marin de l'hémisphère nord capable de voler.", "Le pingouin plonge pour attraper du poisson.", "#e0e7ff"),
    ("gorille", 4, "🦍", "Grand primate majestueux et paisible des forêts tropicales.", "Le gorille se frappe la poitrine.", "#e2e8f0"),
    ("chimpanzé", 4, "🐒", "Singe très doué qui utilise des petits outils en bois.", "Le chimpanzé s'amuse avec ses amis.", "#ffedd5"),
    ("paresseux", 4, "🦥", "Animal qui passe sa vie suspendu à l'envers dans les arbres.", "Le paresseux avance très calmement.", "#dcfce7"),
    ("hérisson", 4, "🦔", "Petite boule à piquants amie des jardiniers.", "Le hérisson chasse les petites limaces.", "#fed7aa"),
    ("libellule", 4, "🪰", "Insecte aux quatre ailes transparentes qui plane au-dessus de l'eau.", "La libellule brille au soleil.", "#cffafe"),
    ("sauterelle", 4, "🦗", "Insecte vert aux grandes pattes arrière qui saute très loin.", "La sauterelle chante dans l'herbe haute.", "#dcfce7"),
    ("corbeau", 4, "🐦‍⬛", "Grand oiseau noir très intelligent avec un cri rauque.", "Le corbeau trouve une petite branche.", "#e2e8f0"),
    ("perroquet", 4, "🦜", "Oiseau multicolore capable d'imiter la voix humaine.", "Le perroquet répète bonjour joyeusement.", "#dcfce7"),
    ("chinchilla", 4, "🐭", "Petit rongeur des Andes avec une fourrure incroyablement douce.", "Le chinchilla fait sa toilette.", "#f1f5f9"),
    ("narval", 4, "🐋", "Cétacé de l'océan Arctique avec une longue défense torsadée.", "La corne du narval fend la banquise.", "#cffafe"),

    # Level 5
    ("hippopotame", 5, "🦛", "Gros animal qui adore se baigner dans les rivières d'Afrique.", "L'hippopotame ouvre sa bouche géante.", "#e2e8f0"),
    ("rhinocéros", 5, "🦏", "Puissant animal avec une corne sur le museau et un RH !", "Le rhinocéros charge dans la plaine.", "#e2e8f0"),
    ("coccinelle", 5, "🐞", "La bête à bon Dieu rouge avec deux CC et deux LL !", "La petite coccinelle a sept points noirs.", "#fee2e2"),
    ("ornithorynque", 5, "🦆", "Animal étonnant d'Australie à bec de canard et queue de castor.", "L'ornithorynque nage dans la rivière.", "#fed7aa"),
    ("dromadaire", 5, "🐪", "Le vaisseau du désert qui possède une seule bosse.", "Le dromadaire traverse les dunes de sable.", "#fef3c7"),
    ("chameau", 5, "🐫", "Grand mammifère du désert qui possède deux grosses bosses.", "Le chameau résiste à la chaleur du désert.", "#fef3c7"),
    ("salamandre", 5, "🦎", "Petit amphibien noir et jaune qui aime l'humidité des forêts.", "La salamandre se cache sous une souche.", "#fef9c3"),
    ("tarentule", 5, "🕷️", "Grande araignée velue très impressionnante mais discrète.", "La tarentule attend au fond de son terrier.", "#ede9fe"),
    ("brontosaure", 5, "🦕", "Dinosaure herbivore géant au très long cou paisible.", "Le brontosaure broute les hautes cimes.", "#dcfce7"),
    ("tyrannosaure", 5, "🦖", "Le redoutable roi des dinosaures aux dents acérées.", "Le tyrannosaure fait trembler le sol.", "#dcfce7"),
    ("caméléon", 5, "🦎", "Merveilleux reptile aux couleurs changeantes et langue télescopique.", "Le caméléon attrape une mouche en un éclair.", "#dcfce7"),
    ("bourdon", 5, "🐝", "Gros insecte velu et doux qui butine en vrombissant.", "Le bourdon récolte le doux nectar.", "#fef9c3"),
    ("albatros", 5, "🪶", "Oiseau marin géant capable de planer des jours entiers sans battre des ailes.", "L'albatros survole les océans déchaînés.", "#e0f2fe"),
    ("étoile de mer", 5, "⭐", "Animal marin en forme d'étoile qui vit sur les rochers.", "L'étoile de mer s'accroche au rocher.", "#fee2e2"),
    ("chevreuil", 5, "🦌", "Petit cervidé très agile et gracieux de nos forêts.", "Le chevreuil disparaît dans le sous-bois.", "#fed7aa"),
    ("sanglier", 5, "🐗", "Cousin sauvage du cochon avec de fortes défenses.", "Le sanglier fouille le sol de la forêt.", "#fed7aa"),
    ("chauve-souris", 5, "🦇", "Seul mammifère capable de voler dans la nuit grâce aux échos.", "La chauve-souris dort la tête en bas.", "#ede9fe"),
]

ALIMENTS = [
    # Level 1
    ("pain", 1, "🥖", "Le boulanger le cuit dans son grand four.", "Une bonne baguette de pain frais.", "#fef3c7"),
    ("lait", 1, "🥛", "Boisson blanche que donne la gentille vache.", "Un grand verre de lait frais.", "#f1f5f9"),
    ("jus", 1, "🧃", "Boisson aux fruits pressés que l'on boit avec une paille.", "Un bon jus de pomme au goûter.", "#ffedd5"),
    ("eau", 1, "💧", "La boisson la plus saine et indispensable pour vivre.", "Je bois de l'eau fraîche.", "#e0f2fe"),
    ("sel", 1, "🧂", "Petits grains blancs qui donnent du goût aux plats.", "On ajoute une pincée de sel.", "#f8fafc"),
    ("riz", 1, "🍚", "Petits grains blancs très nourrissants que l'on cuit à l'eau.", "Un bol de riz chaud.", "#f1f5f9"),
    ("thé", 1, "🍵", "Boisson chaude parfumée préparée avec des feuilles.", "Une tasse de thé à la menthe.", "#ecfccb"),
    ("miel", 1, "🍯", "Doux trésor doré fabriqué par les abeilles.", "Une cuillère de miel sur la tartine.", "#fef9c3"),
    ("noix", 1, "🌰", "Fruit à coque très dure bon pour la mémoire.", "L'écureuil casse une noix.", "#fed7aa"),
    ("kiwi", 1, "🥝", "Fruit tout vert à l'intérieur avec plein de vitamine C.", "Je coupe un kiwi en deux.", "#dcfce7"),
    ("pois", 1, "🫛", "Petite bille verte et sucrée cachée dans sa cosse.", "Les petits pois sont délicieux.", "#dcfce7"),
    ("maïs", 1, "🌽", "Grains jaunes doux qui éclatent pour faire du pop-corn.", "L'épi de maïs est bien grillé.", "#fef9c3"),
    ("fève", 1, "🫘", "Graine potagère ou figurine cachée dans la galette.", "J'ai trouvé la fève dans ma part !", "#fef3c7"),
    ("mûre", 1, "🫐", "Baie noire sauvage que l'on cueille sur les ronces.", "On prépare de la confiture de mûres.", "#f3e8ff"),
    ("chou", 1, "🥬", "Légume tout rond avec de grandes feuilles épaisses.", "Un bon chou vert du jardin.", "#dcfce7"),
    ("tarte", 1, "🥧", "Pâte croustillante garnie de pommes ou de chocolat.", "Une belle tarte dorée au four.", "#fed7aa"),

    # Level 2
    ("pomme", 2, "🍎", "Un fruit croquant souvent rouge ou vert !", "Je croque une belle pomme.", "#fee2e2"),
    ("poire", 2, "🍐", "Un fruit doux et juteux en forme de goutte.", "Une poire bien sucrée.", "#ecfccb"),
    ("glace", 2, "🍦", "Froide et sucrée en cornet ou en pot l'été.", "Une bonne glace à la fraise.", "#fce7f3"),
    ("pêche", 2, "🍑", "Fruit d'été à la peau veloutée et au cœur juteux.", "La pêche sent très bon.", "#ffedd5"),
    ("prune", 2, "🫐", "Petit fruit violet ou doré très sucré.", "Je ramasse une prune sous l'arbre.", "#ede9fe"),
    ("melon", 2, "🍈", "Gros fruit orange très rafraîchissant en été.", "Une tranche de melon bien fraîche.", "#fed7aa"),
    ("mangue", 2, "🥭", "Fruit tropical à la chair orange fondante et sucrée.", "Une mangue mûre à point.", "#fef3c7"),
    ("raisin", 2, "🍇", "Grappe de petits grains sucrés noirs ou blancs.", "Je grignote une grappe de raisin.", "#ede9fe"),
    ("olive", 2, "🫒", "Petit fruit du sud qui donne une huile délicieuse.", "Une pizza garnie de bonnes olives.", "#ecfccb"),
    ("soupe", 2, "🥣", "Mélange de légumes chauds cuits et mixés pour le soir.", "Un grand bol de soupe chaude.", "#fed7aa"),
    ("pâte", 2, "🍝", "Faites de blé, en forme de coquillettes ou de spaghettis.", "Des pâtes au fromage fondant.", "#fef3c7"),
    ("pizza", 2, "🍕", "Pâte ronde italienne cuite au four avec de la tomate et du fromage.", "On partage une bonne pizza.", "#ffedd5"),
    ("purée", 2, "🥔", "Pommes de terre écrasées avec du beurre et du lait.", "La purée forme un petit volcan.", "#fef9c3"),
    ("frites", 2, "🍟", "Bâtonnets de pomme de terre dorés et croustillants.", "Des frites bien chaudes.", "#fef9c3"),
    ("jambon", 2, "🥓", "Tranche rose tendre souvent mise dans les sandwichs.", "Un sandwich au jambon et au beurre.", "#fee2e2"),
    ("poulet", 2, "🍗", "Viande blanche très appréciée rôtie au four le dimanche.", "Le poulet rôti sent délicieusement bon.", "#fed7aa"),
    ("poisson", 2, "🐟", "Aliment sain venu de la mer ou de la rivière.", "Du poisson avec du riz chaud.", "#cffafe"),
    ("beurre", 2, "🧈", "Produit laitier doré que l'on tartine sur le pain.", "Du beurre doux sur du pain frais.", "#fef9c3"),
    ("sucre", 2, "🍬", "Poudre blanche qui apporte de la douceur aux desserts.", "Une cuillère de sucre dans le yaourt.", "#f8fafc"),
    ("farine", 2, "🌾", "Poudre blanche indispensable pour faire du pain et des gâteaux.", "On verse la farine dans le saladier.", "#f1f5f9"),
    ("tomate", 2, "🍅", "Fruit rouge juteux que l'on mange en salade.", "Une tomate mûrie au soleil.", "#fee2e2"),
    ("salade", 2, "🥗", "Feuilles vertes croquantes servies avec une vinaigrette.", "Une grande salade verte.", "#dcfce7"),
    ("radis", 2, "🪴", "Petit légume rose et piquant croquant sous la dent.", "On mange les radis avec du sel et du beurre.", "#fee2e2"),
    ("navet", 2, "🍲", "Légume racine blanc et violet cuit dans le bouillon.", "Le navet cuit dans la marmite.", "#f3e8ff"),
    ("crêpe", 2, "🥞", "Fine galette dorée que l'on fait sauter dans la poêle.", "Je tartine ma crêpe de chocolat.", "#fef3c7"),

    # Level 3
    ("banane", 3, "🍌", "Un fruit jaune courbé que l'on épluche facilement.", "Je mange une banane au goûter.", "#fef9c3"),
    ("carotte", 3, "🥕", "Légume orange croquant qui rend aimable avec deux T !", "Le lapin croque une carotte.", "#ffedd5"),
    ("cerise", 3, "🍒", "Petit fruit rouge et rond souvent attaché par deux.", "Des cerises bien sucrées cueillies sur l'arbre.", "#fee2e2"),
    ("fraise", 3, "🍓", "Un fruit rouge parfumé avec des petits grains extérieurs.", "Une délicieuse fraise bien sucrée.", "#fee2e2"),
    ("orange", 3, "🍊", "Fruit d'hiver juteux qui porte le nom de sa couleur.", "Je bois un jus d'orange pressé.", "#ffedd5"),
    ("gâteau", 3, "🎂", "On souffle des bougies dessus pour son anniversaire !", "Un délicieux gâteau au chocolat.", "#fce7f3"),
    ("ananas", 3, "🍍", "Gros fruit exotique avec un panache de feuilles piquantes.", "L'ananas est doux et acidulé.", "#fef9c3"),
    ("abricot", 3, "🍑", "Fruit orange à la peau douce comme du velours.", "Un abricot sucré cueilli en été.", "#fed7aa"),
    ("citron", 3, "🍋", "Fruit jaune très acide qui donne beaucoup de peps.", "Une goutte de jus de citron.", "#fef9c3"),
    ("avocat", 3, "🥑", "Fruit crémeux à chair verte avec un gros noyau au milieu.", "L'avocat est délicieux avec une vinaigrette.", "#dcfce7"),
    ("brocoli", 3, "🥦", "Légume vert qui ressemble à une forêt de petits arbres.", "Je mange tout mon brocoli.", "#dcfce7"),
    ("haricot", 3, "🫘", "Long légume vert croquant que l'on équeute.", "Des haricots verts cuits à la vapeur.", "#dcfce7"),
    ("poivron", 3, "🫑", "Légume croquant rouge, jaune ou vert.", "Le poivron colore notre assiette.", "#fee2e2"),
    ("oignon", 3, "🧅", "Légume qui parfume les plats mais fait pleurer les yeux !", "On coupe l'oignon en petits dés.", "#fed7aa"),
    ("chocolat", 3, "🍫", "Délice sucré au cacao adoré de tous les enfants.", "Un carré de chocolat noir fondant.", "#fed7aa"),
    ("bonbon", 3, "🍬", "Petite friandise sucrée et colorée pour les grandes fêtes.", "Un bonbon qui pétille sur la langue.", "#fce7f3"),
    ("biscuit", 3, "🍪", "Petit gâteau sec et croquant parfait avec un verre de lait.", "Un biscuit croustillant au chocolat.", "#fed7aa"),
    ("gaufre", 3, "🧇", "Pâtisserie dorée aux alvéoles croustillantes.", "Une gaufre saupoudrée de sucre glace.", "#fef3c7"),
    ("brioche", 3, "🍞", "Pain doux et doré à la mie moelleuse et parfumée.", "Une tranche de brioche dorée au réveil.", "#fef3c7"),
    ("croissant", 3, "🥐", "Viennoiserie feuilletée au beurre en forme de demi-lune.", "Un bon croissant chaud le dimanche matin.", "#fef3c7"),
    ("fromage", 3, "🧀", "Fabriqué avec du lait, à pâte molle ou dure.", "Un morceau de fromage sur du pain.", "#fef9c3"),
    ("yaourt", 3, "🥛", "Dessert lacté crémeux que l'on mange à la cuillère.", "Un yaourt à la vanille.", "#f1f5f9"),
    ("confiture", 3, "🍯", "Fruits cuits longuement avec du sucre pour tartiner.", "De la confiture de fraises maison.", "#fee2e2"),
    ("baguette", 3, "🥖", "Le pain allongé traditionnel de nos boulangeries.", "J'achète une baguette bien croustillante.", "#fef3c7"),
    ("sandwich", 3, "🥪", "Deux tranches de pain garnies pour le pique-nique.", "Un bon sandwich pour la sortie scolaire.", "#fef3c7"),

    # Level 4
    ("pastèque", 4, "🍉", "Énorme fruit vert foncé rempli d'une chair rouge très fraîche.", "Une grosse tranche de pastèque juteuse.", "#fee2e2"),
    ("mandarine", 4, "🍊", "Petit agrume d'hiver facile à éplucher en quartiers.", "La mandarine parfume toute la classe.", "#ffedd5"),
    ("framboise", 4, "🫐", "Petite baie rose tendre faite de minuscules perles.", "Une framboise douce et parfumée.", "#fce7f3"),
    ("myrtille", 4, "🫐", "Petite perle bleue sauvage des montagnes.", "Une délicieuse tarte aux myrtilles.", "#ede9fe"),
    ("noisette", 4, "🌰", "Fruit sec croquant très apprécié des écureuils.", "Une noisette cachée sous la mousse.", "#fed7aa"),
    ("châtaigne", 4, "🌰", "Fruit de l'automne que l'on fait griller au feu de bois.", "Des châtaignes chaudes en hiver.", "#fed7aa"),
    ("champignon", 4, "🍄", "Il pousse sous les arbres et possède un joli chapeau.", "On cuisine une omelette aux champignons.", "#fee2e2"),
    ("artichaut", 4, "🥬", "Légume dont on effeuille les pétales avant d'arriver au cœur.", "L'artichaut se trempe dans la sauce.", "#dcfce7"),
    ("betterave", 4, "🪴", "Légume racine tout rond d'un magnifique rouge violet.", "Une belle salade de betterave rouge.", "#fce7f3"),
    ("courgette", 4, "🥒", "Légume long du potager vert foncé très tendre.", "Une soupe de courgettes au fromage.", "#dcfce7"),
    ("aubergine", 4, "🍆", "Beau légume violet foncé indispensable dans la ratatouille.", "L'aubergine fond dans la casserole.", "#ede9fe"),
    ("épinard", 4, "🥬", "Grandes feuilles vertes réputées pour donner de la force.", "Les épinards sont pleins de fer.", "#dcfce7"),
    ("macaron", 4, "🧁", "Petite gourmandise ronde et colorée fourrée de ganache.", "Un macaron fondant à la pistache.", "#fce7f3"),
    ("éclair", 4, "🥖", "Pâtisserie allongée garnie de crème et recouverte d'un glaçage.", "Un éclair au bon chocolat.", "#fed7aa"),
    ("sucette", 4, "🍭", "Bonbon rond et dur piqué sur un petit bâton.", "Une sucette à la fraise qui dure longtemps.", "#fee2e2"),
    ("cacahuète", 4, "🥜", "Petite graine salée qui pousse sous la terre.", "On partage des cacahuètes à l'apéritif.", "#fed7aa"),
    ("citrouille", 4, "🎃", "Gros légume orange qui sert de lanterne pour Halloween.", "La citrouille d'Halloween brille dans la nuit.", "#ffedd5"),
    ("abricotier", 4, "🌳", "L'arbre fruitier qui produit les abricots dorés.", "L'abricotier est couvert de fleurs blanches.", "#fed7aa"),
    ("cornichon", 4, "🥒", "Petit légume vert croquant conservé dans le vinaigre.", "Un cornichon qui croque dans le burger.", "#dcfce7"),
    ("vinaigre", 4, "🍶", "Liquide acide parfumé qui relève toutes les salades.", "Une goutte de vinaigre dans l'assaisonnement.", "#fee2e2"),

    # Level 5
    ("clémentine", 5, "🍊", "Délicieux petit agrume d'hiver sans pépins facile à peler.", "Je mange une clémentine bien juteuse au goûter.", "#ffedd5"),
    ("chou-fleur", 5, "🥦", "Gros légume d'hiver aux bouquets blancs comme des nuages.", "Un bon gratin de chou-fleur au fromage.", "#f8fafc"),
    ("pamplemousse", 5, "🍊", "Gros agrume rose ou jaune au goût frais et légèrement amer.", "Un demi-pamplemousse au petit déjeuner.", "#fee2e2"),
    ("grenadille", 5, "🍈", "Fruit de la passion exotique rempli de graines acidulées.", "La grenadille apporte un parfum tropical.", "#fef3c7"),
    ("mille-feuille", 5, "🍰", "Gâteau fait de nombreuses couches de pâte croustillante et crème.", "Le mille-feuille craque sous la cuillère.", "#fef3c7"),
    ("viennoiserie", 5, "🥐", "Délices feuilletés et dorés fabriqués chaque matin par l'artisan.", "L'odeur de la viennoiserie chaude attire les gourmands.", "#fed7aa"),
    ("spaghetti", 5, "🍝", "Longues pâtes italiennes que l'on enroule autour de sa fourchette.", "Les spaghettis à la sauce tomate sont prêts.", "#fef9c3"),
    ("tagliatelle", 5, "🍝", "Larges rubans de pâtes fraîches délicieux avec de la crème.", "Un plat de tagliatelles aux champignons.", "#fef9c3"),
    ("profiterole", 5, "🍨", "Petit chou garni de glace à la vanille et nappé de chocolat chaud.", "La profiterole fond dans la bouche.", "#fed7aa"),
    ("marshmallow", 5, "🍢", "Friandise moelleuse et sucrée que l'on fait griller au feu.", "Un marshmallow doré sur la braise.", "#fce7f3"),
    ("mayonnaise", 5, "🥣", "Sauce onctueuse préparée avec du jaune d'œuf, de l'huile et de la moutarde.", "Une cuillère de mayonnaise maison.", "#fef9c3"),
    ("vinaigrette", 5, "🥗", "Sauce légère composée d'huile, de vinaigre et de sel.", "On arrose la salade de bonne vinaigrette.", "#dcfce7"),
    ("betteravier", 5, "🚜", "Cultivateur spécialisé dans la récolte des betteraves sucrières.", "Le betteravier récolte ses racines d'automne.", "#ffedd5"),
    ("châtaignier", 5, "🌳", "Arbre majestueux qui produit les bogues piquantes de châtaignes.", "Le grand châtaignier abrite les oiseaux.", "#fed7aa"),
    ("champignonnière", 5, "🍄", "Lieu obscur et humide où sont cultivés les champignons.", "On visite une ancienne champignonnière.", "#e2e8f0"),
    ("bouillabaisse", 5, "🍲", "Célèbre soupe de poissons traditionnelle du port de Marseille.", "Une bouillabaisse parfumée au safran.", "#fed7aa"),
    ("confiturier", 5, "🍯", "Artisan passionné qui prépare des confitures de fruits rares.", "Le confiturier remue sa grande bassine de cuivre.", "#fee2e2"),
]

OBJETS = [
    # Level 1
    ("lit", 1, "🛏️", "On y dort bien au chaud sous la couette la nuit.", "Je dors dans mon lit confortable.", "#e0f2fe"),
    ("nez", 1, "👃", "Au milieu du visage pour respirer et sentir les bonnes odeurs.", "J'ai un petit nez.", "#fee2e2"),
    ("bras", 1, "💪", "Entre l'épaule et la main, il permet de porter des choses.", "Je plie mon bras musclé.", "#ffedd5"),
    ("sac", 1, "🎒", "On y range ses affaires pour aller à l'école.", "Mon sac à dos est bien fermé.", "#e0e7ff"),
    ("bol", 1, "🥣", "Récipient rond pour boire son chocolat chaud le matin.", "Un bol de chocolat fumant.", "#fee2e2"),
    ("clé", 1, "🔑", "Petit objet en métal pour ouvrir et fermer la serrure.", "J'ai la clé de la maison.", "#fef3c7"),
    ("vis", 1, "🔩", "Petite pièce de métal filetée que l'on tourne avec un tournevis.", "On serre la vis dans le bois.", "#e2e8f0"),
    ("fil", 1, "🧵", "Brin très fin utilisé pour coudre avec une aiguille.", "Un fil rouge pour recoudre le bouton.", "#fee2e2"),
    ("pot", 1, "🪴", "Récipient pour mettre une fleur ou stocker de la confiture.", "Un pot de fleurs sur le balcon.", "#fed7aa"),
    ("mur", 1, "🧱", "Paroi solide qui sépare les pièces de la maison.", "Le mur est peint en jaune clair.", "#fef9c3"),
    ("fer", 1, "🧲", "Métal solide ou appareil servant à repasser les vêtements.", "Un fer à repasser tout chaud.", "#e2e8f0"),
    ("dé", 1, "🎲", "Petit cube avec des points de 1 à 6 pour les jeux de société.", "Je lance le dé et je fais six !", "#f8fafc"),
    ("bac", 1, "📦", "Grande boîte pour ranger les jouets dans la chambre.", "Je range mes briques dans le bac.", "#e0f2fe"),
    ("arc", 1, "🏹", "Arme en bois courbé qui propulse des flèches.", "Robin des Bois tire avec son arc.", "#fed7aa"),
    ("verre", 1, "🥛", "Récipient transparent pour boire de l'eau.", "Un verre d'eau bien fraîche.", "#cffafe"),
    ("bus", 1, "🚌", "Grand véhicule pour emmener toute la classe en sortie.", "Le bus arrive à l'arrêt.", "#fef3c7"),

    # Level 2
    ("livre", 2, "📖", "Rempli d'histoires avec des pages à tourner.", "Je lis un beau livre de contes.", "#ede9fe"),
    ("stylo", 2, "🖊️", "Outil rempli d'encre pour écrire proprement sur son cahier.", "J'écris mon prénom avec mon stylo.", "#e0e7ff"),
    ("table", 2, "🪑", "Meuble à quatre pieds sur lequel on pose son assiette ou son cahier.", "Nous mangeons tous à table.", "#fef3c7"),
    ("porte", 2, "🚪", "On l'ouvre par la poignée pour entrer dans la classe.", "Ferme la porte s'il te plaît.", "#fed7aa"),
    ("robot", 2, "🤖", "Machine électronique amusante qui obéit aux ordres.", "Mon robot avance tout seul.", "#e2e8f0"),
    ("tasse", 2, "☕", "Petit récipient avec une anse pour boire une tisane chaude.", "Une jolie tasse décorée.", "#fee2e2"),
    ("boîte", 2, "📦", "Objet en carton ou en métal qui s'ouvre avec un couvercle.", "Une boîte remplie de trésors.", "#fed7aa"),
    ("lampe", 2, "💡", "Elle s'allume pour éclairer la pièce quand il fait nuit.", "La lampe éclaire mon bureau.", "#fef9c3"),
    ("tapis", 2, "🧶", "Tissu épais posé par terre pour réchauffer les pieds.", "Un tapis tout doux dans le salon.", "#ede9fe"),
    ("fauteuil", 2, "🛋️", "Siège large et très confortable avec des accoudoirs.", "Grand-père lit dans son fauteuil.", "#fed7aa"),
    ("chaise", 2, "🪑", "Siège sur lequel on s'assoit pour travailler ou manger.", "Assieds-toi sur ta chaise.", "#fed7aa"),
    ("tiroir", 2, "🗄️", "Compartiment qui coulisse dans le meuble pour ranger.", "Le tiroir est plein de stylos.", "#f1f5f9"),
    ("armoire", 2, "🚪", "Grand meuble haut où l'on suspend ses vêtements.", "Je range mon manteau dans l'armoire.", "#fed7aa"),
    ("miroir", 2, "🪞", "Surface brillante qui reflète notre visage.", "Je me regarde dans le miroir.", "#cffafe"),
    ("savon", 2, "🧼", "Il mousse dans les mains et lave très proprement avec de l'eau.", "Le savon sent bon la lavande.", "#fce7f3"),
    ("peigne", 2, "🪮", "Objet à dents fines pour démêler les cheveux le matin.", "Je me coiffe avec mon peigne.", "#fef3c7"),
    ("brosse", 2, "🪥", "Elle nettoie les dents ou discipline les mèches de cheveux.", "Une brosse à dents toute neuve.", "#e0f2fe"),
    ("balai", 2, "🧹", "Outil à long manche qui sert à ramasser les miettes au sol.", "On passe un coup de balai dans la cuisine.", "#fed7aa"),
    ("valise", 2, "🧳", "Grand bagage dans lequel on prépare ses habits de vacances.", "Ma valise est prête pour le voyage.", "#fee2e2"),
    ("montre", 2, "⌚", "Petit cadran que l'on porte au poignet pour lire l'heure.", "Ma montre indique huit heures.", "#e0e7ff"),
    ("horloge", 2, "⏰", "Cadran mural qui sonne le tic-tac des secondes.", "L'horloge sonne la fin de la classe.", "#fef9c3"),
    ("gomme", 2, "🧼", "Petit morceau de caoutchouc qui efface les traits de crayon.", "La gomme efface mon erreur.", "#fce7f3"),
    ("règle", 2, "📏", "Outil plat et gradué pour tracer des lignes bien droites.", "Je trace un trait à la règle.", "#fef9c3"),
    ("colle", 2, "🧴", "Bâton blanc pour coller les feuilles dans le cahier.", "Un tube de colle pour l'atelier.", "#e0f2fe"),
    ("cahier", 2, "📒", "Ensemble de pages quadrillées pour faire ses exercices.", "J'ouvre mon cahier de poésie.", "#fef3c7"),

    # Level 3
    ("maison", 3, "🏠", "L'endroit chaleureux où l'on vit en famille.", "Bienvenue dans ma maison accueillante.", "#ffedd5"),
    ("ballon", 3, "⚽", "Sphère en cuir gonflée d'air avec deux L pour jouer.", "On tire dans le ballon pour marquer.", "#f1f5f9"),
    ("cartable", 3, "🎒", "Grand sac d'écolier porté sur le dos pour transporter ses livres.", "Mon cartable est bien rangé.", "#e0e7ff"),
    ("ciseaux", 3, "✂️", "Outil à deux lames articulées pour découper proprement le papier.", "Découpe le contour avec tes ciseaux.", "#e2e8f0"),
    ("pinceau", 3, "🖌️", "Poils doux fixés sur un manche pour peindre en couleur.", "Je trempe mon pinceau dans la gouache.", "#fed7aa"),
    ("tableau", 3, "🖼️", "Grande surface noire ou blanche sur laquelle écrit le maître.", "Le maître écrit la date au tableau.", "#dcfce7"),
    ("feutre", 3, "🖍️", "Crayon à mine d'encre colorée pour faire de beaux dessins.", "Je colorie le soleil avec un feutre jaune.", "#fef9c3"),
    ("crayon", 3, "✏️", "Bâtonnet de bois contenant une mine de graphite.", "Je taille mon crayon de papier.", "#fed7aa"),
    ("trousse", 3, "👝", "Petite pochette zippée pour ranger ses stylos et sa gomme.", "Ma trousse est pleine de couleurs.", "#fce7f3"),
    ("compas", 3, "📐", "Instrument à deux branches servant à tracer de parfaits cercles.", "Le compas tourne sur la feuille.", "#e2e8f0"),
    ("éponge", 3, "🧽", "Objet très poreux qui absorbe l'eau pour nettoyer l'ardoise.", "L'éponge nettoie le tableau d'un geste.", "#fef9c3"),
    ("bouteille", 3, "🍾", "Récipient allongé avec un goulot pour conserver les boissons.", "Une bouteille d'eau fraîche pour le sport.", "#e0f2fe"),
    ("poubelle", 3, "🗑️", "Bac dans lequel on jette les déchets pour garder la classe propre.", "Jette le papier à la poubelle.", "#e2e8f0"),
    ("lunettes", 3, "👓", "Deux verres correcteurs posés sur le nez pour mieux voir.", "Je porte mes lunettes pour lire.", "#ede9fe"),
    ("chapeau", 3, "🎩", "Couvre-chef élégant que l'on pose sur sa tête.", "Le magicien sort un lapin de son chapeau.", "#e0e7ff"),
    ("manteau", 3, "🧥", "Vêtement chaud et épais qu'on enfile en hiver.", "Je boutonne mon gros manteau.", "#fed7aa"),
    ("écharpe", 3, "🧣", "Bande de laine tricotée pour protéger son cou du froid.", "Une écharpe toute douce autour du cou.", "#fee2e2"),
    ("bonnet", 3, "🧢", "Coiffe en laine qui protège la tête et les oreilles.", "Je mets mon bonnet pour aller dans la neige.", "#e0e7ff"),
    ("bottes", 3, "👢", "Chaussures montantes imperméables pour sauter dans les flaques.", "Mes bottes en caoutchouc rouge.", "#fee2e2"),
    ("baskets", 3, "👟", "Chaussures de sport très confortables pour courir vite.", "Je lace mes baskets pour la récréation.", "#f1f5f9"),
    ("pantalon", 3, "👖", "Vêtement à deux jambes qui descend jusqu'aux chevilles.", "Mon pantalon en jean bleu.", "#dbeafe"),
    ("chemise", 3, "👔", "Vêtement boutonné avec un col et des manches longues.", "Une chemise blanche bien repassée.", "#f8fafc"),
    ("guitare", 3, "🎸", "Instrument de musique à six cordes que l'on pince.", "Je joue une chanson à la guitare.", "#fed7aa"),
    ("tambour", 3, "🥁", "Instrument de percussion sur lequel on tape en rythme avec des baguettes.", "Le tambour bat la mesure.", "#fee2e2"),
    ("clavier", 3, "⌨️", "Planche garnie de touches avec des lettres pour taper du texte.", "Mes doigts volent sur le clavier.", "#f1f5f9"),

    # Level 4
    ("parapluie", 4, "☂️", "Dôme de toile imperméable que l'on déploie sous l'averse.", "J'ouvre mon parapluie pour rester au sec.", "#ede9fe"),
    ("château", 4, "🏰", "Grande forteresse médiévale flanquée de hautes tours.", "Le roi habite dans son château fort.", "#fef3c7"),
    ("bouteille", 4, "🍾", "Récipient en verre étanche avec EILLE.", "Une bouteille de jus d'orange.", "#e0f2fe"),
    ("cartable", 4, "🎒", "Sac rigide d'écolier avec des bretelles rembourrées.", "Le cartable contient tous mes manuels scolaires.", "#e0e7ff"),
    ("trompette", 4, "🎺", "Instrument en cuivre brillant qui produit un son éclatant.", "La fanfare fait résonner la trompette.", "#fef9c3"),
    ("violon", 4, "🎻", "Instrument en bois à quatre cordes frottées avec un archet.", "Le violoniste joue une mélodie émouvante.", "#fed7aa"),
    ("microscope", 4, "🔬", "Appareil scientifique qui grossit l'infiniment petit.", "J'observe une cellule au microscope.", "#cffafe"),
    ("télescope", 4, "🔭", "Grand instrument d'optique pour observer les étoiles la nuit.", "Le télescope dévoile les cratères de la Lune.", "#ede9fe"),
    ("téléphone", 4, "📱", "Petit appareil électronique tactile pour appeler ses proches.", "J'appelle mes grands-parents au téléphone.", "#f1f5f9"),
    ("télévision", 4, "📺", "Grand écran familial pour regarder des documentaires passionnants.", "Nous regardons un dessin animé à la télévision.", "#e2e8f0"),
    ("baignoire", 4, "🛁", "Grand bac émaillé où l'on prend un bon bain moussant.", "L'eau chaude coule dans la baignoire.", "#cffafe"),
    ("serviette", 4, "🧖", "Linge doux et absorbant pour se sécher après la douche.", "Une grande serviette de bain moelleuse.", "#fce7f3"),
    ("dentifrice", 4, "🪥", "Pâte nettoyante parfumée à la menthe pour les dents.", "Je dépose une noisette de dentifrice.", "#e0f2fe"),
    ("toboggan", 4, "🛝", "Piste inclinée du parc où les enfants glissent avec joie.", "Je glisse sur le grand toboggan.", "#fef3c7"),
    ("balançoire", 4, "🎠", "Siège suspendu par deux cordes pour voler dans le ciel.", "La balançoire monte très haut.", "#fef3c7"),
    ("ventilateur", 4, "🌀", "Appareil à hélices qui brasse l'air frais en été.", "Le ventilateur souffle une douce brise.", "#e0f2fe"),
    ("radiateur", 4, "🔥", "Appareil métallique qui chauffe doucement la pièce en hiver.", "Le chat dort près du radiateur chaud.", "#fee2e2"),
    ("casque audio", 4, "🎧", "Écouteurs confortables que l'on pose sur ses oreilles.", "J'écoute une histoire avec mon casque.", "#ede9fe"),
    ("dictionnaire", 4, "📖", "Gros livre contenant la définition de milliers de mots.", "Je cherche un mot rare dans le dictionnaire.", "#fef3c7"),
    ("encyclopédie", 4, "📚", "Ouvrage complet expliquant tous les secrets du monde.", "Cette encyclopédie regorge d'images magnifiques.", "#ede9fe"),

    # Level 5
    ("ordinateur", 5, "💻", "Machine puissante dotée d'un écran, d'une souris et d'un clavier.", "J'apprends à taper sur mon ordinateur.", "#f1f5f9"),
    ("bibliothèque", 5, "📚", "Grande armoire ou salle entière remplie d'étagères de livres.", "Nous empruntons des albums à la bibliothèque.", "#ede9fe"),
    ("anniversaire", 5, "🎉", "Jour festif exceptionnel où l'on souffle ses bougies avec ses amis.", "Joyeux anniversaire et plein de bonheur !", "#fce7f3"),
    ("labyrinthe", 5, "🌀", "Parcours complexe aux allées tortueuses dont on cherche l'issue.", "On trouve la sortie secrète du labyrinthe.", "#dcfce7"),
    ("squelette", 5, "💀", "L'armature solide de tous les os articulés de notre corps.", "Le squelette nous permet de courir et sauter.", "#f8fafc"),
    ("kaléidoscope", 5, "🔮", "Tube magique qui crée des figures colorées symétriques à l'infini.", "Je regarde les formes féeriques du kaléidoscope.", "#fce7f3"),
    ("taille-crayon", 5, "✏️", "Petit boîtier contenant une lame qui affine la mine des crayons.", "Mon taille-crayon recueille tous les copeaux.", "#fef3c7"),
    ("microphone", 5, "🎤", "Appareil électronique qui amplifie la voix des chanteurs.", "La chanteuse parle dans son microphone.", "#f1f5f9"),
    ("réfrigérateur", 5, "🧊", "Grande armoire froide qui conserve les aliments bien au frais.", "Le lait reste frais dans le réfrigérateur.", "#cffafe"),
    ("trampoline", 5, "🤸", "Toile élastique tendue sur laquelle on fait de gigantesques bonds.", "Je saute très haut sur le trampoline.", "#dcfce7"),
    ("thermomètre", 5, "🌡️", "Instrument précis gradué qui mesure la température de l'air.", "Le thermomètre indique vingt degrés.", "#fee2e2"),
    ("appareil photo", 5, "📷", "Boîtier magique qui immortalise les plus beaux souvenirs.", "Clic-clac, je prends une jolie photo de famille.", "#e2e8f0"),
    ("machine à laver", 5, "🫧", "Appareil ménager dont le tambour lave le linge de la maison.", "La machine à laver fait des bulles de savon.", "#cffafe"),
    ("porte-monnaie", 5, "👛", "Petite pochette où l'on garde ses pièces de monnaie.", "Je range mes sous dans mon porte-monnaie.", "#fce7f3"),
    ("boussole", 5, "🧭", "Cadran dont l'aiguille aimantée pointe toujours vers le Nord.", "La boussole indique la direction du pôle Nord.", "#fef3c7"),
    ("microscope", 5, "🔬", "Instrument optique de précision utilisé par les chercheurs.", "Le savant examine une goutte d'eau au microscope.", "#cffafe"),
    ("sculpture", 5, "🗿", "Œuvre d'art tridimensionnelle taillée dans la pierre ou le bois.", "Une magnifique sculpture exposée au musée.", "#e2e8f0"),
]

NATURE = [
    # Level 1
    ("lune", 1, "🌙", "Elle brille d'une douce lueur argentée dans le ciel la nuit.", "La pleine lune éclaire notre nuit.", "#ede9fe"),
    ("mer", 1, "🌊", "Étendue immense d'eau bleue salée avec des vagues.", "On plonge joyeusement dans la mer bleue.", "#cffafe"),
    ("lac", 1, "🏞️", "Grand bassin d'eau douce entouré de montagnes ou de forêts.", "Les canards glissent sur le lac calme.", "#cffafe"),
    ("pré", 1, "🌾", "Terrain d'herbe tendre où les vaches et les moutons broutent.", "Les vaches paissent dans le pré fleuri.", "#dcfce7"),
    ("eau", 1, "💧", "Source précieuse et limpide de toute la vie sur Terre.", "Une goutte d'eau pure de la source.", "#e0f2fe"),
    ("ciel", 1, "🌌", "Le grand dôme bleu au-dessus de nos têtes habité par les nuages.", "Le ciel est d'un bleu éclatant.", "#e0e7ff"),
    ("sol", 1, "🌱", "La surface de la terre où germent les graines.", "La petite graine germe dans le sol.", "#fed7aa"),
    ("vent", 1, "💨", "L'air en mouvement qui fait bruisser les feuilles des arbres.", "Le vent fait voler mon cerf-volant.", "#e0f2fe"),
    ("gel", 1, "🧊", "Froid intense qui transforme l'eau liquide en glace transparente.", "Le gel blanchit l'herbe le matin.", "#cffafe"),
    ("feu", 1, "🔥", "Flammes chaleureuses qui éclairent et réchauffent le foyer.", "Le feu crépite doucement dans la cheminée.", "#fee2e2"),
    ("roc", 1, "🪨", "Gros bloc de pierre très dur dressé dans la nature.", "La chèvre se hisse sur le roc.", "#e2e8f0"),
    ("pin", 1, "🌲", "Arbre toujours vert qui sent bon la résine et porte des pommes de pin.", "Le grand pin résiste au grand vent.", "#dcfce7"),
    ("île", 1, "🏝️", "Terre entourée d'eau de tous les côtés avec un chapeau sur le I !", "L'île déserte est bordée de palmiers.", "#fef3c7"),
    ("bois", 1, "🪵", "Matière du tronc des arbres ou petit groupe d'arbres.", "Nous nous promenons dans les bois calmes.", "#fed7aa"),
    ("lys", 1, "⚜️", "Fleur blanche royale au parfum délicat et majestueux.", "Le lys fleurit au milieu du jardin.", "#f8fafc"),
    ("pic", 1, "⛰️", "Le sommet pointu d'une haute montagne qui touche le ciel.", "Le pic enneigé brille au soleil levant.", "#e2e8f0"),

    # Level 2
    ("fleur", 2, "🌸", "Elle éclot au printemps et embaume le jardin de ses couleurs.", "Une jolie fleur rose dans l'herbe.", "#fce7f3"),
    ("arbre", 2, "🌳", "Il a de profondes racines, un tronc de bois et de belles feuilles vertes.", "Les oiseaux chantent dans le grand arbre.", "#dcfce7"),
    ("nuage", 2, "☁️", "Gros coussin blanc de vapeur suspendu dans le ciel bleu.", "Le nuage défile au gré du vent.", "#f1f5f9"),
    ("soleil", 2, "☀️", "Notre étoile dorée qui réchauffe et éclaire toute la Terre.", "Le soleil brille chaleureusement.", "#fef9c3"),
    ("rose", 2, "🌹", "Fleur très parfumée aux pétales soyeux et à la tige épineuse.", "Une belle rose rouge épanouie.", "#fee2e2"),
    ("herbe", 2, "🌱", "Tapis végétal vert et frais qui couvre les champs.", "L'herbe fraîche est douce sous les pieds nus.", "#dcfce7"),
    ("forêt", 2, "🌲", "Grand domaine boisé peuplé d'arbres centenaires et d'animaux.", "Les cerfs vivent cachés dans la forêt.", "#dcfce7"),
    ("plage", 2, "🏖️", "Bord de mer recouvert de sable fin où l'on ramasse des coquillages.", "On fait de magnifiques châteaux de sable sur la plage.", "#fef3c7"),
    ("sable", 2, "⏳", "Poussière dorée de coquillages et de roches au bord de l'eau.", "Le sable chaud glisse entre mes doigts.", "#fef3c7"),
    ("vague", 2, "🌊", "Ondulation de la mer qui vient rouler et écumer sur le rivage.", "La vague s'écrase sur les galets.", "#cffafe"),
    ("galet", 2, "🪨", "Caillou tout rond et lisse poli par les vagues de la mer.", "Je fais des ricochets avec un galet plat.", "#e2e8f0"),
    ("pluie", 2, "🌧️", "Gouttes d'eau bienfaisantes qui tombent des nuages pour arroser les plantes.", "La pluie nourrit les jardins assoiffés.", "#e0f2fe"),
    ("neige", 2, "❄️", "Flocons de glace légers et blancs qui forment un manteau silencieux.", "La neige recouvre les toits du village.", "#f8fafc"),
    ("orage", 2, "⛈️", "Grand phénomène météo avec des éclairs, du tonnerre et de la pluie.", "L'orage gronde au loin dans la vallée.", "#ede9fe"),
    ("éclair", 2, "⚡", "Trait de lumière fulgurant qui traverse le ciel d'orage.", "L'éclair illumine toute la nuit.", "#fef9c3"),
    ("terre", 2, "🌍", "Notre belle planète bleue ou la terre fertile du jardin.", "La Terre tourne autour du Soleil.", "#dcfce7"),
    ("dune", 2, "🏜️", "Grande colline de sable façonnée par les rafales de vent.", "Nous grimpons au sommet de la dune.", "#fef3c7"),
    ("rivière", 2, "🏞️", "Cours d'eau naturel qui serpente avant de rejoindre le fleuve.", "L'eau claire de la rivière coule doucement.", "#cffafe"),
    ("fleuve", 2, "🌊", "Grand cours d'eau puissant qui se jette directement dans la mer.", "Les péniches naviguent sur le grand fleuve.", "#dbeafe"),
    ("feuille", 2, "🍃", "Élément vert de la branche qui capte la lumière du soleil.", "La feuille dorée voltige en automne.", "#dcfce7"),
    ("branche", 2, "🪵", "Bras de bois qui s'élance du tronc de l'arbre.", "L'oiseau fait son nid sur une branche solide.", "#fed7aa"),
    ("graine", 2, "🌱", "Tout petit trésor végétal qui donnera une grande plante.", "On sème la graine dans la bonne terre.", "#dcfce7"),
    ("racine", 2, "🌿", "Partie souterraine de la plante qui puise l'eau dans la terre.", "Les racines de l'arbre s'enfoncent profondément.", "#fed7aa"),
    ("tulipe", 2, "🌷", "Fleur printanière en forme de calice aux couleurs éclatantes.", "Les tulipes fleurissent dans le parc.", "#fee2e2"),
    ("buisson", 2, "🪴", "Touffe d'arbustes touffus où aiment se cacher les lapins.", "Le lapin se dissimule dans le buisson.", "#dcfce7"),

    # Level 3
    ("étoile", 3, "⭐", "Astre lointain et étincelant qui illumine le ciel nocturne.", "Fais un vœu quand tu vois une étoile filante.", "#fef9c3"),
    ("cascade", 3, "🌊", "Chute d'eau vive qui dégringole d'une haute falaise rocheuse.", "Le bruit puissant de la cascade d'eau fraîche.", "#cffafe"),
    ("volcan", 3, "🌋", "Montagne impressionnante d'où jaillit parfois de la lave incandescente.", "La lave rouge coule le long du volcan.", "#fee2e2"),
    ("falaise", 3, "🧗", "Paroi rocheuse abrupte qui surplombe majestueusement les flots.", "Les mouettes nichent au creux de la falaise.", "#e2e8f0"),
    ("colline", 3, "⛰️", "Petite montagne douce et arrondie facile à gravir.", "La maison se dresse au sommet de la colline.", "#dcfce7"),
    ("vallée", 3, "🏞️", "Espace creux et verdoyant situé entre deux chaînes de montagnes.", "Le village est niché au fond de la vallée.", "#dcfce7"),
    ("sentier", 3, "🥾", "Petit chemin de terre tracé pour la randonnée en pleine nature.", "Nous suivons le sentier à travers les sapins.", "#fed7aa"),
    ("prairie", 3, "🌾", "Grande étendue d'herbe sauvage constellée de fleurs multicolores.", "Les papillons butinent dans la prairie.", "#dcfce7"),
    ("glacier", 3, "🧊", "Immense fleuve de glace éternelle descendant lentement des sommets.", "Le glacier scintille sous les rayons du soleil.", "#cffafe"),
    ("banquise", 3, "❄️", "Étendue d'eau de mer gelée où vivent les ours polaires.", "L'ours blanc marche sur la banquise arctique.", "#f8fafc"),
    ("savane", 3, "🦁", "Vaste plaine herbeuse africaine ponctuée de baobabs.", "Les zèbres traversent la savane dorée.", "#fef3c7"),
    ("jungle", 3, "🌴", "Forêt tropicale luxuriante, très dense et humide.", "Les singes se balancent dans la jungle.", "#dcfce7"),
    ("désert", 3, "🏜️", "Vaste région aride où les précipitations sont extrêmement rares.", "Le soleil tape fort sur le désert de sable.", "#fef3c7"),
    ("tempête", 3, "🌪️", "Violente tourmente de vent et de pluie balayant le paysage.", "La tempête agite les cimes des arbres.", "#e2e8f0"),
    ("brouillard", 3, "🌫️", "Nuage épais posé au ras du sol qui masque la vue.", "Le brouillard matinal enveloppe la campagne.", "#f1f5f9"),
    ("rocher", 3, "🪨", "Masse de pierre robuste servant de perchoir aux oiseaux.", "Le lézard se dore sur le rocher.", "#e2e8f0"),
    ("ruisseau", 3, "🫧", "Petit cours d'eau chantant qui serpente à travers la clairière.", "Le ruisseau murmure entre les cailloux.", "#cffafe"),
    ("source", 3, "💧", "Endroit magique où l'eau pure jaillit naturellement de la terre.", "Nous buvons l'eau glacée de la source.", "#e0f2fe"),
    ("clairière", 3, "🪵", "Espace découvert et ensoleillé au milieu d'une forêt dense.", "Une biche apparaît dans la clairière.", "#dcfce7"),
    ("sommet", 3, "🏔️", "Le point culminant d'une montagne touchant l'horizon.", "Nous atteignons le sommet après une belle marche.", "#e2e8f0"),
    ("caverne", 3, "🦇", "Cavité naturelle creusée dans la roche d'une montagne.", "La caverne abrite les chauves-souris.", "#e2e8f0"),
    ("cristal", 3, "💎", "Minéral transparent aux arêtes parfaites qui brille de mille feux.", "Un beau cristal trouvé dans la grotte.", "#cffafe"),
    ("aurore", 3, "🌅", "Le premier éclat de lumière dorée juste avant le lever du soleil.", "L'aurore annonce une belle journée ensoleillée.", "#ffedd5"),
    ("crépuscule", 3, "🌇", "Le moment poétique où le soleil disparaît derrière l'horizon.", "Le ciel s'empourpre au crépuscule.", "#ede9fe"),
    ("flaque", 3, "🌧️", "Petite mare d'eau de pluie dans laquelle on adore sauter en bottes.", "Je saute à pieds joints dans la flaque.", "#cffafe"),

    # Level 4
    ("montagne", 4, "⛰️", "Très haute colline rocheuse couronnée de neiges éternelles.", "La haute montagne tutoie les nuages blancs.", "#e2e8f0"),
    ("champignon", 4, "🍄", "Il pousse dans les sous-bois humides sous son joli chapeau.", "Un beau champignon rouge à pois blancs.", "#fee2e2"),
    ("arc-en-ciel", 4, "🌈", "Sept couleurs magiques unies quand le soleil traverse la pluie.", "Un arc-en-ciel radieux illumine la vallée.", "#fef3c7"),
    ("tournesol", 4, "🌻", "Grande fleur solaire dont la tête pivote pour suivre la lumière.", "Le tournesol sourit au zénith.", "#fef9c3"),
    ("pissenlit", 4, "🌼", "Fleur jaune dont on aime souffler sur l'aigrette plumeuse.", "Je souffle sur les graines du pissenlit.", "#fef9c3"),
    ("coquelicot", 4, "🌺", "Fleur sauvage d'un rouge écarlate ondulant au vent des blés.", "Les coquelicots tachent de rouge les champs de blé.", "#fee2e2"),
    ("nénuphar", 4, "🪷", "Grande feuille plate flottant sur l'eau où se perche la grenouille.", "La grenouille verte coasse sur son nénuphar.", "#dcfce7"),
    ("stalactite", 4, "🧊", "Concrétion de calcaire pointue suspendue au plafond des grottes.", "Une stalactite millénaire goutte lentement.", "#cffafe"),
    ("stalagmite", 4, "🧊", "Pilier calcaire qui monte patiemment du sol d'une grotte.", "La stalagmite s'élève goutte après goutte.", "#cffafe"),
    ("ouragan", 4, "🌀", "Cyclone tropical géant aux vents d'une force extraordinaire.", "L'ouragan soulève des vagues gigantesques.", "#e0f2fe"),
    ("tornade", 4, "🌪️", "Colonne d'air tourbillonnant à grande vitesse dévastant tout.", "La tornade tourbillonne au-dessus de la plaine.", "#e2e8f0"),
    ("avalanche", 4, "❄️", "Masse immense de neige qui dévale à toute vitesse la pente.", "L'avalanche gronde le long du versant nord.", "#f8fafc"),
    ("bambouseraie", 4, "🎋", "Forêt dense de hauts bambous verts se balançant dans le vent.", "Le panda se régale au cœur de la bambouseraie.", "#dcfce7"),
    ("végétation", 4, "🌿", "L'ensemble luxuriant de toutes les plantes d'une région.", "La végétation tropicale est d'une grande richesse.", "#dcfce7"),
    ("marégraphe", 4, "🌊", "Appareil côtier qui enregistre la hauteur des marées.", "Le marégraphe mesure le flux et le reflux de l'océan.", "#cffafe"),
    ("astéroïde", 4, "☄️", "Petit corps rocheux qui voyage à travers l'espace lointain.", "L'astéroïde frôle l'orbite de la planète.", "#ede9fe"),
    ("nébuleuse", 4, "🌌", "Nuage géant de gaz interstellaire où naissent de nouvelles étoiles.", "Le télescope spatial photographie une magnifique nébuleuse.", "#ede9fe"),
    ("constellation", 4, "✨", "Dessin imaginaire tracé par un groupe d'étoiles dans la nuit.", "La Grande Ourse est une constellation facile à repérer.", "#ede9fe"),
    ("clair de lune", 4, "🌕", "Lumière douce et argentée qui éclaire les paysages nocturnes.", "Nous marchons paisiblement au clair de lune.", "#ede9fe"),
    ("banquise", 4, "🧊", "Couche de glace flottante formée par le gel de l'eau de mer.", "Les morses se reposent sur la banquise.", "#cffafe"),

    # Level 5
    ("environnement", 5, "🌱", "La nature fragile et précieuse que chaque enfant doit protéger.", "Prenons soin de notre environnement tous les jours.", "#dcfce7"),
    ("écosystème", 5, "🌿", "Équilibre vivant et harmonieux entre les êtres vivants et leur milieu.", "La forêt forme un écosystème remarquable.", "#dcfce7"),
    ("biodiversité", 5, "🦋", "L'immense et merveilleuse variété de toutes les espèces vivantes.", "La sauvegarde de la biodiversité est vitale pour la Terre.", "#dcfce7"),
    ("photosynthèse", 5, "🍃", "Procédé magique grâce auquel les feuilles fabriquent de l'oxygène pur.", "Grâce à la photosynthèse, les forêts purifient l'air.", "#dcfce7"),
    ("aurore boréale", 5, "🌌", "Féerie de voiles lumineux verts et violets dansant dans le ciel du Nord.", "L'aurore boréale illumine le ciel de Laponie.", "#cffafe"),
    ("météorologue", 5, "🌦️", "Spécialiste scientifique qui étudie et prévoit la météo de demain.", "Le météorologue annonce un grand beau temps pour le week-end.", "#e0f2fe"),
    ("constellation", 5, "✨", "Figure mythologique céleste reliant des étoiles scintillantes.", "Cassiopée est une magnifique constellation en forme de W.", "#ede9fe"),
    ("nénuphar géant", 5, "🪷", "Plante aquatique d'Amazonie dont la feuille peut supporter un enfant.", "Le nénuphar géant flotte sur l'eau du fleuve.", "#dcfce7"),
    ("chlorophylle", 5, "🌱", "Pigment vert présent dans les feuilles des plantes qui capte la lumière.", "La chlorophylle donne sa belle couleur verte aux feuilles.", "#dcfce7"),
    ("stalagmitique", 5, "🏛️", "Relatif aux concrétions calcaires montant du sol d'une caverne.", "La forêt stalagmitique est un trésor géologique.", "#e2e8f0"),
    ("foudre", 5, "⚡", "Décharge électrique surpuissante éclatant entre l'orage et la Terre.", "La foudre tombe sur le paratonnerre.", "#fef9c3"),
    ("crépusculaire", 5, "🌇", "Qui se produit à la tombée de la nuit lorsque le ciel s'assombrit.", "Les chauves-souris entament leur vol crépusculaire.", "#ede9fe"),
    ("lithosphère", 5, "🌍", "L'enveloppe terrestre rocheuse et solide sur laquelle nous vivons.", "La lithosphère est découpée en grandes plaques tectoniques.", "#fed7aa"),
    ("stratosphère", 5, "✈️", "Couche haute de l'atmosphère terrestre où la météo reste sereine.", "Les grands avions voyagent dans la basse stratosphère.", "#e0e7ff"),
    ("paléontologie", 5, "🦖", "Science passionnante consacrée à l'étude des fossiles anciens.", "Le chercheur en paléontologie découvre un crâne de dinosaure.", "#fed7aa"),
    ("hydrosphère", 5, "💧", "L'ensemble de toutes les eaux liquides, solides et gazeuses de la Terre.", "L'hydrosphère couvre la majeure partie du globe.", "#cffafe"),
    ("cristallisation", 5, "❄️", "Transformation magique de l'eau en flocons de neige géométriques.", "La cristallisation crée de minuscules dentelles de givre.", "#f8fafc"),
]

TRANSPORTS = [
    # Level 1
    ("bus", 1, "🚌", "Grand véhicule collectif qui transporte les écoliers à l'école.", "Le bus scolaire s'arrête devant la barrière.", "#fef3c7"),
    ("vélo", 1, "🚲", "Véhicule à deux roues que l'on fait avancer en pédalant fort.", "Je fais du vélo sur la piste cyclable.", "#dbeafe"),
    ("car", 1, "🚍", "Grand autocar confortable pour voyager d'une ville à une autre.", "Nous montons dans le car pour l'excursion.", "#fef3c7"),
    ("van", 1, "🚐", "Fourgonnette spacieuse et pratique pour partir en week-end.", "On range les sacs dans le van familial.", "#e0e7ff"),
    ("bac", 1, "⛴️", "Bateau à fond plat qui permet de traverser un fleuve d'une rive à l'autre.", "Le bac transporte les voitures sur l'eau.", "#cffafe"),
    ("ski", 1, "🎿", "Longues planches lisses attachées aux pieds pour glisser sur la neige.", "Je chausse mes skis sur la piste enneigée.", "#f8fafc"),
    ("luge", 1, "🛷", "Petit traîneau de bois ou de plastique pour dévaler les pentes.", "Nous glissons à toute vitesse sur la luge.", "#fee2e2"),
    ("char", 1, "🏛️", "Véhicule antique tiré par des chevaux ou charrette de foin.", "Le char d'or défile lors du grand carnaval.", "#fed7aa"),
    ("rame", 1, "🛶", "Pagaie de bois tenue à deux mains pour faire avancer la barque.", "On plonge la rame dans l'eau claire.", "#fed7aa"),
    ("rail", 1, "🛤️", "Barre d'acier sur laquelle roulent sans dévier les trains.", "Le train file à grande allure sur les rails.", "#e2e8f0"),
    ("taxi", 1, "🚕", "Voiture avec un voyant lumineux sur le toit pour transporter les voyageurs.", "Le taxi nous dépose juste devant la gare.", "#fef9c3"),
    ("tram", 1, "🚊", "Rame électrique circulant sur des rails au milieu de la ville.", "Le tramway s'arrête doucement à la station.", "#dbeafe"),
    ("pont", 1, "🌉", "Ouvrage solide permettant aux voitures et piétons de franchir un obstacle.", "Le train franchit le grand pont au-dessus du fleuve.", "#e2e8f0"),
    ("port", 1, "⚓", "Bassin abrité où les bateaux s'amarrent le long des quais.", "Les voiliers sont bien rangés dans le port.", "#cffafe"),
    ("quai", 1, "🚉", "Allée surélevée où les passagers attendent l'arrivée de leur train.", "J'attends sur le quai numéro deux.", "#f1f5f9"),
    ("cale", 1, "🚢", "Le fond spacieux d'un navire où l'on charge les marchandises.", "Les matelots descendent les caisses dans la cale.", "#fed7aa"),

    # Level 2
    ("avion", 2, "✈️", "Grand oiseau de métal doté de deux ailes pour voler à travers les nuages.", "L'avion vole très haut dans le ciel bleu.", "#e0e7ff"),
    ("train", 2, "🚆", "Long convoi de wagons tracté par une locomotive sur les rails.", "Tchou tchou, le train entre majestueusement en gare.", "#e2e8f0"),
    ("métro", 2, "🚇", "Train souterrain rapide qui dessert toutes les stations de la ville.", "Nous prenons le métro pour aller au musée.", "#e0e7ff"),
    ("moto", 2, "🏍️", "Véhicule à deux roues motorisé sur lequel on roule avec un casque.", "Le motard pilote prudemment sa moto.", "#fee2e2"),
    ("quad", 2, "🛞", "Petit engin tout-terrain à quatre grosses roues crantées.", "Le quad franchit facilement les chemins boueux.", "#fed7aa"),
    ("jeep", 2, "🚙", "Robuste voiture tout-terrain idéale pour les safaris.", "La jeep avance au milieu de la savane.", "#dcfce7"),
    ("fusée", 2, "🚀", "Engin spatial propulsé par des réacteurs pour rejoindre les étoiles.", "La fusée décolle dans un grand nuage blanc.", "#fee2e2"),
    ("canot", 2, "🛶", "Petite embarcation légère manœuvrée avec des pagaies.", "Le canot glisse silencieusement sur le lac.", "#cffafe"),
    ("barque", 2, "🚣", "Bateau en bois idéal pour pêcher paisiblement au fil de l'eau.", "On détache la barque du petit ponton.", "#fed7aa"),
    ("kayak", 2, "🛶", "Petite embarcation sportive fermée menée avec une double pagaie.", "Il descend les rapides agiles en kayak.", "#fed7aa"),
    ("canoë", 2, "🛶", "Embarcation ouverte manœuvrée avec une pagaie simple.", "Nous pagayons ensemble dans le canoë.", "#fed7aa"),
    ("cargo", 2, "🚢", "Grand navire de commerce transportant des milliers de conteneurs.", "Le cargo traverse les mers lointaines.", "#dbeafe"),
    ("ferry", 2, "⛴️", "Gros navire assurant le transport régulier des voyageurs et de leurs voitures.", "Le ferry accoste au port de l'île.", "#cffafe"),
    ("yacht", 2, "🛥️", "Bateau de plaisance luxueux et très rapide.", "Le yacht jette l'ancre dans la baie abritée.", "#f8fafc"),
    ("wagon", 2, "🚃", "Compartiment roulant du train où s'assoient confortablement les passagers.", "Nous montons dans le wagon numéro cinq.", "#e2e8f0"),
    ("cabine", 2, "🚡", "Nacelle suspendue qui transporte les skieurs vers les sommets.", "La cabine survole les sapins enneigés.", "#fee2e2"),
    ("patins", 2, "🛼", "Chaussures munies de roulettes ou d'une lame pour glisser sur la glace.", "Je fais des pirouettes avec mes patins.", "#fce7f3"),
    ("skate", 2, "🛹", "Planche courte montée sur quatre roulettes pour faire des figures.", "Il s'entraîne au skatepark sur son skate.", "#fef3c7"),
    ("radeau", 2, "🪵", "Plateforme flottante faite de troncs de bois attachés ensemble.", "Le radeau descend doucement la rivière.", "#fed7aa"),
    ("voilier", 2, "⛵", "Bateau élégant qui utilise la force du vent dans ses toiles blanches.", "Le voilier prend le vent du large.", "#dbeafe"),
    ("navette", 2, "🚐", "Petit véhicule effectuant sans arrêt des allers-retours réguliers.", "La navette nous emmène à l'aéroport.", "#fef3c7"),
    ("mobylette", 2, "🛵", "Petit deux-roues motorisé équipé de pédales.", "La mobylette pétarade doucement dans la ruelle.", "#e0e7ff"),
    ("remorque", 2, "🛒", "Chariot attelé à l'arrière d'un véhicule pour transporter du matériel.", "On accroche la remorque à la voiture.", "#e2e8f0"),
    ("scooter", 2, "🛵", "Deux-roues motorisé avec un plancher plat pour poser ses pieds.", "Il roule en scooter avec son casque bien attaché.", "#fee2e2"),
    ("tracteur", 2, "🚜", "Gros véhicule agricole à énormes roues qui laboure les champs.", "Le tracteur vert tire la charrue dans le champ.", "#dcfce7"),

    # Level 3
    ("voiture", 3, "🚗", "Véhicule à quatre roues et moteur pour voyager en famille.", "On s'attache bien dans la voiture avant de partir.", "#fee2e2"),
    ("camion", 3, "🚛", "Grand véhicule très puissant qui transporte de lourdes marchandises.", "Le camion livre les cartons au supermarché.", "#fef3c7"),
    ("bateau", 3, "⛵", "Embarcation qui flotte sur l'eau grâce à sa coque étanche.", "Le bateau navigue paisiblement sur les flots.", "#cffafe"),
    ("chalutier", 3, "🎣", "Bateau de pêche équipé de grands filets pour ramener du poisson.", "Le chalutier rentre au port au petit matin.", "#dbeafe"),
    ("péniche", 3, "🚢", "Long bateau à fond plat qui navigue sur les canaux et les rivières.", "La péniche franchit l'écluse doucement.", "#fed7aa"),
    ("gondole", 3, "🛶", "Embarcation noire traditionnelle et poétique des canaux de Venise.", "Le gondolier manœuvre sa gondole avec son long aviron.", "#f1f5f9"),
    ("pédalo", 3, "🛶", "Petit bateau de vacances que l'on fait avancer en pédalant sur l'eau.", "On fait un tour de pédalo sur le lac ensoleillé.", "#fef9c3"),
    ("side-car", 3, "🏍️", "Moto équipée d'une nacelle latérale pour accueillir un passager.", "Le copilote est bien assis dans le side-car.", "#fee2e2"),
    ("tandem", 3, "🚲", "Bicyclette à deux selles et deux paires de pédales pour rouler à deux.", "Nous pédalons en harmonie sur notre tandem.", "#dbeafe"),
    ("draisienne", 3, "🚲", "Petit vélo sans pédales parfait pour que les tout-petits apprennent l'équilibre.", "Le petit garçon roule vite sur sa draisienne.", "#fce7f3"),
    ("tricycle", 3, "🛞", "Vélo stable à trois roues idéal pour les jeunes enfants.", "Elle fait le tour du jardin sur son tricycle.", "#fee2e2"),
    ("caravane", 3, "🚐", "Maison roulante remorquée par une voiture pour faire du camping.", "Nous installons la caravane sous les pins.", "#fef3c7"),
    ("chariot", 3, "🛒", "Véhicule à quatre roues servant à déplacer de lourdes charges.", "On remplit le chariot de provisions.", "#e2e8f0"),
    ("funiculaire", 3, "🚠", "Wagon tracté par un câble pour gravir une pente très raide.", "Le funiculaire monte jusqu'au sommet de la colline.", "#fee2e2"),
    ("deltaplane", 3, "🪂", "Aile triangulaire légère permettant de planer dans les airs comme un oiseau.", "Le pilote s'élance de la falaise en deltaplane.", "#cffafe"),
    ("monoplace", 3, "🏎️", "Voiture de course rapide dotée d'un seul siège pour le pilote.", "La monoplace de Formule 1 franchit la ligne d'arrivée.", "#fee2e2"),
    ("trottinette", 3, "🛴", "Planche à deux roues et guidon sur laquelle on pousse du pied.", "Je file à toute allure sur ma trottinette.", "#fee2e2"),
    ("voilier", 3, "⛵", "Navire gracieux aux voiles blanches gonflées par le vent.", "Le voilier contourne le phare du port.", "#dbeafe"),
    ("sous-marin", 3, "🤿", "Navire exceptionnel capable de plonger au plus profond des mers.", "Le sous-marin explore les abysses océaniques.", "#dbeafe"),
    ("fourgon", 3, "🚐", "Véhicule utilitaire fermé pour transporter des colis.", "Le livreur descend les paquets de son fourgon.", "#f1f5f9"),
    ("ambulance", 3, "🚑", "Véhicule d'urgence blanche avec un gyrophare bleu pour secourir les malades.", "L'ambulance file avec sa sirène deux-tons.", "#f8fafc"),
    ("pompiers", 3, "🚒", "Grand camion rouge équipé d'une échelle télescopique et de lances à eau.", "Le camion des pompiers part éteindre un feu.", "#fee2e2"),
    ("motoneige", 3, "❄️", "Véhicule motorisé à chenille pour filer sur la neige épaisse.", "La motoneige trace sa piste dans le grand nord.", "#f8fafc"),
    ("paquebot", 3, "🛳️", "Immense ville flottante de plusieurs étages naviguant sur les océans.", "Le gigantesque paquebot quitte le port.", "#f8fafc"),
    ("parachute", 3, "🪂", "Grande coupole de tissu qui freine la chute dans les airs.", "Le parachutiste atterrit en douceur dans le champ.", "#cffafe"),

    # Level 4
    ("hélicoptère", 4, "🚁", "Engin volant spectaculaire grâce aux pales tournantes de son rotor.", "L'hélicoptère de secours se pose sur l'hôpital.", "#fee2e2"),
    ("locomotive", 4, "🚂", "Le moteur puissant en tête de train qui tracte tous les wagons.", "La locomotive à vapeur siffle dans la vallée.", "#e2e8f0"),
    ("montgolfière", 4, "🎈", "Immense ballon d'air chaud sous lequel est suspendue une nacelle d'osier.", "La montgolfière s'élève silencieusement dans le ciel du matin.", "#ffedd5"),
    ("téléphérique", 4, "🚡", "Nacelle suspendue à un très long câble d'acier reliant deux montagnes.", "Le téléphérique nous conduit au sommet enneigé.", "#e0e7ff"),
    ("aéroglisseur", 4, "🚤", "Véhicule sur coussin d'air capable de glisser sur l'eau comme sur la terre.", "L'aéroglisseur traverse la baie à pleine vitesse.", "#cffafe"),
    ("catamaran", 4, "⛵", "Bateau de course ou de croisière très stable équipé de deux coques parallèles.", "Le catamaran glisse sur l'eau sans gîter.", "#dbeafe"),
    ("brise-glace", 4, "🚢", "Navire renforcé d'une proue spéciale pour fendre la banquise polaire.", "Le brise-glace ouvre une voie dans les glaces.", "#cffafe"),
    ("skateboard", 4, "🛹", "Planche à roulettes sur laquelle on réalise d'acrobatiques sauts.", "Il maîtrise parfaitement son skateboard.", "#fef3c7"),
    ("dirigeable", 4, "🎈", "Aéronef allongé plus léger que l'air gonflé d'un gaz protecteur.", "Le grand dirigeable plane au-dessus du stade.", "#f1f5f9"),
    ("chasse-neige", 4, "🚜", "Camion équipé d'une grande lame frontale pour dégager la route enneigée.", "Le chasse-neige déblaie la route du col.", "#fef9c3"),
    ("semi-remorque", 4, "🚛", "Énorme camion de transport routier composé d'un tracteur et d'une remorque.", "Le semi-remorque roule sur l'autoroute.", "#e2e8f0"),
    ("bateau-mouche", 4, "🛥️", "Bateau panoramique vitré permettant de visiter Paris sur la Seine.", "Nous admirons la Tour Eiffel depuis le bateau-mouche.", "#cffafe"),
    ("bicyclette", 4, "🚲", "Le nom élégant et traditionnel de notre cher vélo à pédales.", "Une promenade printanière à bicyclette.", "#dbeafe"),
    ("navette spatiale", 4, "🚀", "Vaisseau réutilisable capable de voyager dans l'orbite de la Terre.", "La navette spatiale revient de sa mission.", "#f8fafc"),
    ("hydroglisseur", 4, "🚤", "Bateau à fond plat propulsé par une gigantesque hélice aérienne.", "L'hydroglisseur survole les marais de Floride.", "#e0f2fe"),
    ("trottinette électrique", 4, "🛴", "Engin urbain moderne équipé d'une batterie et d'un petit moteur silencieux.", "Il circule en trottinette électrique avec prudence.", "#fee2e2"),
    ("camion-citerne", 4, "🚛", "Poids lourd doté d'une grande cuve métallique pour acheminer les liquides.", "Le camion-citerne approvisionne la station.", "#e2e8f0"),
    ("diligence", 4, "🐴", "Grande voiture attelée d'autrefois qui transportait courriers et voyageurs.", "La diligence traverse les plaines de l'Ouest.", "#fed7aa"),
    ("porte-conteneurs", 4, "🚢", "Géant des mers chargé de milliers de boîtes métalliques colorées.", "Le porte-conteneurs entre dans le grand port marchand.", "#dbeafe"),
    ("side-car cross", 4, "🏍️", "Course spectaculaire de motos à trois roues sur piste tout-terrain.", "Les pilotes de side-car négocient le virage serré.", "#fed7aa"),

    # Level 5
    ("astronaute", 5, "👨‍🚀", "Explorateur courageux qui voyage dans l'espace en combinaison pressurisée.", "L'astronaute flotte en apesanteur dans la station spatiale.", "#e0e7ff"),
    ("porte-avions", 5, "🚢", "Navire militaire géant doté d'une véritable piste de décollage en pleine mer.", "L'avion de chasse apponte sur le porte-avions.", "#e2e8f0"),
    ("submersible", 5, "🤿", "Petit engin sous-marin d'exploration scientifique pour les très grandes profondeurs.", "Le submersible explore la fosse marine abyssale.", "#dbeafe"),
    ("camping-car", 5, "🚐", "Véhicule aménagé avec lits, cuisine et salon pour voyager en toute liberté.", "Nous partons en vacances à bord de notre camping-car.", "#fef3c7"),
    ("aéronef", 5, "✈️", "Terme désignant tout appareil capable de se soutenir et circuler dans les airs.", "Cet aéronef futuriste fonctionne à l'énergie solaire.", "#e0e7ff"),
    ("fusée lunaire", 5, "🚀", "Puissant lanceur spatial conçu pour acheminer des humains jusqu'à la Lune.", "La fusée lunaire s'élance vers les étoiles.", "#f8fafc"),
    ("vaisseau spatial", 5, "🛸", "Engin imaginaire ou futuriste explorant les galaxies lointaines.", "Le vaisseau spatial active sa propulsion interstellaire.", "#ede9fe"),
    ("téléphérique urbain", 5, "🚡", "Transport par câble suspendu moderne survolant le trafic des grandes villes.", "Le téléphérique urbain offre une vue imprenable sur les toits.", "#e0e7ff"),
    ("navette autonome", 5, "🤖", "Petit minibus électrique circulant tout seul sans chauffeur grâce à ses capteurs.", "La navette autonome dépose les passagers à l'hôpital.", "#cffafe"),
    ("hydroptère", 5, "⛵", "Bateau révolutionnaire doté d'ailes sous-marines qui le font voler au-dessus de l'eau.", "L'hydroptère bat le record de vitesse à la voile.", "#dbeafe"),
    ("quadricycle", 5, "🏎️", "Véhicule léger à quatre roues motorisé idéal pour la ville.", "Ce petit quadricycle électrique ne pollue pas.", "#dcfce7"),
    ("char à voile", 5, "⛵", "Engin à trois roues gréé d'une voile qui glisse à toute allure sur le sable mouillé.", "Le char à voile file sur l'immense plage à marée basse.", "#fef3c7"),
    ("parapentiste", 5, "🪂", "Pilote qui s'élance du haut d'un versant accroché sous une grande voile souple.", "Le parapentiste s'élève dans les courants d'air chaud.", "#cffafe"),
    ("spationaute", 5, "🚀", "Nom donné aux astronautes européens explorant le cosmos.", "Le spationaute effectue des expériences scientifiques à bord.", "#e0e7ff"),
    ("bicyclette cargo", 5, "🚲", "Vélo rallongé doté d'une grande caisse avant pour transporter deux enfants.", "Maman conduit les enfants à l'école en vélo cargo.", "#dbeafe"),
    ("motoneigiste", 5, "❄️", "Conducteur chevronné guidant son attelage à chenilles sur les neiges du Grand Nord.", "Le motoneigiste trace sa piste à travers la toundra blanche.", "#f8fafc"),
    ("locotracteur", 5, "🚜", "Petit engin ferroviaire puissant servant à manœuvrer les wagons dans la gare de triage.", "Le locotracteur range les rames de wagons de fret.", "#fef3c7"),
]

# Summary and duplicate checks:
categories = {
    'animaux': ANIMAUX,
    'aliments': ALIMENTS,
    'objets': OBJETS,
    'nature': NATURE,
    'transports': TRANSPORTS
}

all_words = []
used_ids = set()

for cat_name, word_list in categories.items():
    print(f"Checking category: {cat_name} (initial count: {len(word_list)})")
    cat_words = []
    cat_seen = set()
    for item in word_list:
        word, level, emoji, hint, example, color = item
        clean_word = word.strip().lower()
        if clean_word in cat_seen:
            continue
        cat_seen.add(clean_word)

        # ID: slugify
        base_id = slugify(clean_word)
        word_id = base_id
        idx = 2
        while word_id in used_ids:
            word_id = f"{base_id}_{idx}"
            idx += 1
        used_ids.add(word_id)

        obj = {
            "id": word_id,
            "word": word.strip(),
            "level": level,
            "category": cat_name,
            "emoji": emoji,
            "hint": hint,
            "example": example,
            "color": color
        }
        cat_words.append(obj)
        all_words.append(obj)
    print(f" -> Unique in {cat_name}: {len(cat_words)}")

print(f"\nTotal words generated: {len(all_words)}")
